# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 73b72f45106bfeaecbefa75037981dd4c2192ab916f7d27c34ecda544a93782ccd88cbabb1a8b5cddc9d03f85e3cc3b0b9219ce9bfb0d71c833f65fdb51c4736

test:
  domain_name: example.com 
  secret_key_base: 556ad7fc0dcee42dde15e976b697373aacd446952ab38b37ba067d031bfc5bf4c1fd942dc6d21e3c62e5500d95d03b8551e517434c25210477e4934405982abb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
